library: /home/john/.config/beets/library.db
directory: /home/john/Music
plugins: lastgenre ftintitle fetchart embedart smartplaylist replaygain discogs info duplicates rewrite echonest missing
art_filename: folder
original_date: yes

replaygain:
    backend: gstreamer

import:
    write: yes
    move: yes

fetchart:
    cautious: true
    cover_names: front cover folder

rewrite:
    albumartist .*Dave Brubeck.*: Dave Brubeck
    albumartist_sort .*Brubeck, Dave.*: Brubeck, Dave

paths:
    default: %asciify{%if{$albumartist_sort,$albumartist_sort,$albumartist}}/%asciify{$album}%if{$albumdisambig, ($albumdisambig)}%aunique{albumartist album albumdisambig,year} (%if{$original_year,$original_year,$year})/$track %asciify{$title}

echonest:
    codegen: /home/john/Programs/echoprint-codegen-4.12/echoprint-codegen

smartplaylist:
    relative_to: ~/Music
    playlist_dir: ~/Playlists
    playlists:
        - name: High-Res.m3u
          query: 'samplerate:96000'
